endpoints:
  - name: Hello darkness my old friend
    path: /rpc/v0
    method: POST
    routes:
      - name: domain.io
        catch:
          host: domain.io
          headers:
            - name: Authorization
              value: "^.*\\S.*"
          params:
            - name: token
              value: "^.*\\S.*"
        dest:
          host: localhost
          port: 1234
        plugins:
          - type: request-transformer
            enabled: true
            config:
              replace:
                headers:
                  - name: Authorization
                    value: "Bearer JWT"
              add:
                headers:
                  - name: Custom-Header
                    value: Hello
  - name: Test Graph endpoint
    path: /subgraphs
    method: ANY
    routes:
      - name: Mainnet TheGraph
        catch:
          host: mainnet.thegraph.node.glif.io
        dest:
          host: localhost
          port: 1234
        plugins: []
